--- Makefile.old	2012-05-09 10:50:52.000000000 -0500
+++ Makefile	2012-05-09 10:51:18.000000000 -0500
@@ -63,6 +63,8 @@
 	rm -rf autom4te.cache config.log config.status config.mak
 
 deb:
+  rm -rf debian/control
+  make -f debian/rules debian/control
 	debuild -uc -us -b
 
 tgz: config.mak clean
